"""add admins table

Revision ID: 6ec3778aedad
Revises: f88881a2daae
Create Date: 2026-04-02 12:46:50.502275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ec3778aedad'
down_revision: Union[str, Sequence[str], None] = 'f88881a2daae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.alter_column('classes', 'subject',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_unique_constraint('uq_class_identity', 'classes', ['subject', 'class_number', 'professor'])
    op.alter_column('match_runs', 'weights_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_match_runs_student_created'), table_name='match_runs')
    op.create_index(op.f('ix_match_runs_id'), 'match_runs', ['id'], unique=False)
    op.create_index(op.f('ix_match_runs_student_id'), 'match_runs', ['student_id'], unique=False)
    op.drop_index(op.f('ix_matches_run_rank'), table_name='matches')
    op.drop_index(op.f('ix_matches_student_score'), table_name='matches')
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_run_id'), 'matches', ['run_id'], unique=False)
    op.create_index(op.f('ix_matches_student_id'), 'matches', ['student_id'], unique=False)
    op.create_index(op.f('ix_matches_tutor_id'), 'matches', ['tutor_id'], unique=False)
    op.alter_column('notifications', 'payload_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_embeddings_entity_field'), table_name='user_embeddings')
    op.drop_constraint(op.f('user_embeddings_user_id_entity_type_field_name_model_name_key'), 'user_embeddings', type_='unique')
    op.create_index(op.f('ix_user_embeddings_id'), 'user_embeddings', ['id'], unique=False)
    op.create_unique_constraint('uq_user_embedding_slot', 'user_embeddings', ['user_id', 'entity_type', 'field_name', 'model_name'])
    op.create_index(op.f('ix_user_notification_settings_user_id'), 'user_notification_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.drop_constraint('uq_user_embedding_slot', 'user_embeddings', type_='unique')
    op.drop_index(op.f('ix_user_embeddings_id'), table_name='user_embeddings')
    op.create_unique_constraint(op.f('user_embeddings_user_id_entity_type_field_name_model_name_key'), 'user_embeddings', ['user_id', 'entity_type', 'field_name', 'model_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_embeddings_entity_field'), 'user_embeddings', ['entity_type', 'field_name'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('notifications', 'payload_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_matches_tutor_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_student_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_run_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.create_index(op.f('ix_matches_student_score'), 'matches', ['student_id', sa.literal_column('similarity_score DESC')], unique=False)
    op.create_index(op.f('ix_matches_run_rank'), 'matches', ['run_id', 'rank'], unique=False)
    op.drop_index(op.f('ix_match_runs_student_id'), table_name='match_runs')
    op.drop_index(op.f('ix_match_runs_id'), table_name='match_runs')
    op.create_index(op.f('ix_match_runs_student_created'), 'match_runs', ['student_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('match_runs', 'weights_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('uq_class_identity', 'classes', type_='unique')
    op.alter_column('classes', 'subject',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
