"""schema drift check

Revision ID: 927a68287367
Revises: c3f8a9d2e4b1
Create Date: 2026-04-02 13:49:05.020971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '927a68287367'
down_revision: Union[str, Sequence[str], None] = 'c3f8a9d2e4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS user_device_tokens (
            id SERIAL NOT NULL,
            user_id INTEGER NOT NULL,
            token VARCHAR(255) NOT NULL,
            platform VARCHAR(32),
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
            CONSTRAINT uq_user_device_token_value UNIQUE (token)
        );
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_user_device_tokens_id ON user_device_tokens (id);"
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_user_device_tokens_user_id
        ON user_device_tokens (user_id);
        """
    )
    op.alter_column('classes', 'subject',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('classes', 'class_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.execute("ALTER TABLE classes DROP CONSTRAINT IF EXISTS uq_class_identity;")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_class_identity'
            ) THEN
                ALTER TABLE classes
                ADD CONSTRAINT uq_class_identity
                UNIQUE (subject, class_number, professor);
            END IF;
        END $$;
        """
    )
    op.execute("ALTER TABLE classes DROP COLUMN IF EXISTS course_code;")
    op.alter_column('match_runs', 'weights_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.execute("DROP INDEX IF EXISTS ix_match_runs_student_created;")
    op.execute("CREATE INDEX IF NOT EXISTS ix_match_runs_id ON match_runs (id);")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_match_runs_student_id ON match_runs (student_id);"
    )
    op.execute("DROP INDEX IF EXISTS ix_matches_run_rank;")
    op.execute("DROP INDEX IF EXISTS ix_matches_student_score;")
    op.execute("CREATE INDEX IF NOT EXISTS ix_matches_id ON matches (id);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_matches_run_id ON matches (run_id);")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_matches_student_id ON matches (student_id);"
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_matches_tutor_id ON matches (tutor_id);")
    op.alter_column('notifications', 'payload_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.execute("DROP INDEX IF EXISTS ix_notifications_user_created;")
    op.execute("DROP INDEX IF EXISTS ix_notifications_user_unread;")
    op.execute("CREATE INDEX IF NOT EXISTS ix_notifications_id ON notifications (id);")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications (user_id);"
    )
    op.execute("DROP INDEX IF EXISTS ix_user_embeddings_entity_field;")
    op.execute(
        """
        ALTER TABLE user_embeddings
        DROP CONSTRAINT IF EXISTS user_embeddings_user_id_entity_type_field_name_model_name_key;
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_user_embeddings_id ON user_embeddings (id);"
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_user_embedding_slot'
            ) THEN
                ALTER TABLE user_embeddings
                ADD CONSTRAINT uq_user_embedding_slot
                UNIQUE (user_id, entity_type, field_name, model_name);
            END IF;
        END $$;
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_user_notification_settings_user_id
        ON user_notification_settings (user_id);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.drop_constraint('uq_user_embedding_slot', 'user_embeddings', type_='unique')
    op.drop_index(op.f('ix_user_embeddings_id'), table_name='user_embeddings')
    op.create_unique_constraint(op.f('user_embeddings_user_id_entity_type_field_name_model_name_key'), 'user_embeddings', ['user_id', 'entity_type', 'field_name', 'model_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_embeddings_entity_field'), 'user_embeddings', ['entity_type', 'field_name'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('notifications', 'payload_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_matches_tutor_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_student_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_run_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.create_index(op.f('ix_matches_student_score'), 'matches', ['student_id', sa.literal_column('similarity_score DESC')], unique=False)
    op.create_index(op.f('ix_matches_run_rank'), 'matches', ['run_id', 'rank'], unique=False)
    op.drop_index(op.f('ix_match_runs_student_id'), table_name='match_runs')
    op.drop_index(op.f('ix_match_runs_id'), table_name='match_runs')
    op.create_index(op.f('ix_match_runs_student_created'), 'match_runs', ['student_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('match_runs', 'weights_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('classes', sa.Column('course_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint('uq_class_identity', 'classes', type_='unique')
    op.create_unique_constraint(op.f('uq_class_identity'), 'classes', ['subject', 'course_code', 'professor'], postgresql_nulls_not_distinct=False)
    op.alter_column('classes', 'class_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('classes', 'subject',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.execute("DROP INDEX IF EXISTS ix_user_device_tokens_user_id;")
    op.execute("DROP INDEX IF EXISTS ix_user_device_tokens_id;")
    op.execute("DROP TABLE IF EXISTS user_device_tokens;")
    # ### end Alembic commands ###
