"""add student_reviews table

Revision ID: b1c2d3e4f5a6
Revises: a12f4c6d9e31
Create Date: 2026-04-29 18:55:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b1c2d3e4f5a6"
down_revision: Union[str, Sequence[str], None] = "a12f4c6d9e31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.student_reviews (
            review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            student_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
            review_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            review_text TEXT NOT NULL,
            rating DOUBLE PRECISION NOT NULL
        );
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_student_reviews_student_id
        ON public.student_reviews (student_id);
        """
    )
    op.execute(
        """
        ALTER TABLE public.student_reviews
        ADD CONSTRAINT ck_student_reviews_rating_range
        CHECK (rating >= 0.0 AND rating <= 5.0)
        NOT VALID;
        """
    )
    op.execute(
        """
        ALTER TABLE public.student_reviews
        VALIDATE CONSTRAINT ck_student_reviews_rating_range;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        ALTER TABLE public.student_reviews
        DROP CONSTRAINT IF EXISTS ck_student_reviews_rating_range;
        """
    )
    op.execute(
        """
        DROP TABLE IF EXISTS public.student_reviews;
        """
    )

